import type { BadgeDef } from '../types';

export const BADGES: BadgeDef[] = [
  {
    id:    'first_draft',
    name:  'First Steps',
    desc:  'Complete your first draft',
    glyph: '🏀',
    tier:  'Bronze',
    cond:  s => s.stats.drafts >= 1,
  },
  {
    id:    'first_win',
    name:  'Bracket Buster',
    desc:  'Win a playoff game',
    glyph: '✦',
    tier:  'Bronze',
    cond:  s => s.stats.wins >= 1,
  },
  {
    id:    'finals',
    name:  'Conference Champ',
    desc:  'Reach the NBA Finals',
    glyph: '★',
    tier:  'Silver',
    cond:  s => s.stats.bestRound >= 3,
  },
  {
    id:    'ring',
    name:  'Ring Bearer',
    desc:  'Win a championship',
    glyph: '💍',
    tier:  'Gold',
    cond:  s => s.stats.titles >= 1,
  },
  {
    id:    'grinder',
    name:  'Grinder',
    desc:  'Play 10 playoff runs',
    glyph: '⛏',
    tier:  'Silver',
    cond:  s => s.stats.runs >= 10,
  },
  {
    id:    'hot',
    name:  'Hot Hand',
    desc:  'Win 3 games in one run',
    glyph: '🔥',
    tier:  'Silver',
    cond:  s => s.stats.maxWinStreak >= 3,
  },
  {
    id:    'diamond',
    name:  'Diamond Hands',
    desc:  'Roster a 90+ OVR (Diamond)',
    glyph: '💎',
    tier:  'Diamond',
    cond:  s => Math.max(s.stats.topOvr, s.stats.bestPull) >= 90,
  },
  {
    id:    'legend',
    name:  'Crown Jewel',
    desc:  'Roster a 99 OVR (Legend)',
    glyph: '👑',
    tier:  'Legend',
    cond:  s => Math.max(s.stats.topOvr, s.stats.bestPull) >= 99,
  },
  {
    id:    'loyal',
    name:  'Loyal',
    desc:  'Reach a 7-day login streak',
    glyph: '🔥',
    tier:  'Gold',
    cond:  s => s.streak >= 7,
  },
  {
    id:    'devoted',
    name:  'Devoted',
    desc:  'Reach a 30-day login streak',
    glyph: '🏛',
    tier:  'Legend',
    cond:  s => s.streak >= 30,
  },
  {
    id:    'hofwin',
    name:  'Iron Will',
    desc:  'Win a title on Hall of Fame',
    glyph: '⚔',
    tier:  'Legend',
    cond:  s => !!s.stats.hofTitle,
  },
  {
    id:    'rich',
    name:  'Loaded',
    desc:  'Bank 2,000 coins',
    glyph: '◎',
    tier:  'Gold',
    cond:  s => s.coins >= 2000,
  },
];
